---
deployment:
  tasks:
    - export DEPLOYPATH=/home/noorgeec/noorgee.pk/stayora/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R gallery.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
